"""add password change field to users

Revision ID: ad9c47533d9f
Revises: 92f3a8dbe1b9
Create Date: 2025-11-26 16:29:23.980360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9c47533d9f'
down_revision: Union[str, Sequence[str], None] = '92f3a8dbe1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('needs_password_change', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'needs_password_change')
    # ### end Alembic commands ###
