"""add totp information to users

Revision ID: d166888ea097
Revises: ad9c47533d9f
Create Date: 2025-11-27 21:26:03.783708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd166888ea097'
down_revision: Union[str, Sequence[str], None] = 'ad9c47533d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'totp_enabled')
    # ### end Alembic commands ###
